CC=g++
CPPFLAGS=-std=gnu++11 -m64 -I./include/
LDFLAGS=-Wl,-R,/home/moelrue/dbgpub/lib -m64 -L/home/moelrue/dbgpub/lib -lesp_sdk_lib -lesp_server_lib

all: dbag_publisher

dbag_publisher: dbag_publisher.o 

